## Kindle Review Sentiment Analysis

#### Best Practises

1. Preprocessing and Cleaning
2. Train Test Split
3. BOW, TFIDF, Word2Vec
4. Train ML algorithms

In [60]:
# load dataset
import pandas as pd

df=pd.read_csv("all_kindle_review.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [61]:
df = df[['reviewText', 'rating']]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [62]:
df.shape

(12000, 2)

In [63]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [64]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [65]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [66]:
# Preprocessing

In [67]:
# positive review is 1 and negative review is 0
df['rating'] = df['rating'].apply(lambda x: 0 if x < 3 else 1)

In [68]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [69]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [70]:
# 1. Lowercase
df['reviewText'] = df['reviewText'].str.lower()

In [71]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [72]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from bs4 import BeautifulSoup

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ilya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [73]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

In [74]:
df.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [75]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ilya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [76]:
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join([lemmatizer.lemmatize(word) for word in x.split()]))

In [77]:
df.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [78]:
# Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['reviewText'], df['rating'], test_size=0.2)

In [79]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [81]:
import gensim
from gensim.models import Word2Vec, KeyedVectors
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [82]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

words = []

for sentence in X_train:
    sentence_token= sent_tokenize(sentence)
    for word in sentence_token:
        words.append(simple_preprocess(word))

words_test = []

for sentence in X_test:
    sentence_token= sent_tokenize(sentence)
    for word in sentence_token:
        words_test.append(simple_preprocess(word))

In [83]:
words

[['super',
  'short',
  'hot',
  'wet',
  'story',
  'bought',
  'accident',
  'thanks',
  'one',
  'click',
  'thought',
  'free',
  'paid',
  'cent',
  'upset',
  'paid',
  'story',
  'super',
  'short',
  'soon',
  'getting',
  'ended',
  'total',
  'jip'],
 ['competent',
  'thriller',
  'succeeds',
  'level',
  'economically',
  'written',
  'authoritative',
  'newspaper',
  'newsroom',
  'statehouse',
  'journalism',
  'character',
  'skillfully',
  'drawn',
  'slightly',
  'cliched',
  'every',
  'newsroom',
  'fiction',
  'alcoholic',
  'burnout',
  'onetime',
  'star',
  'reporter',
  'last',
  'chancethe',
  'clockspring',
  'tension',
  'suspense',
  'well',
  'developed',
  'though',
  'moralizing',
  'rapacious',
  'nature',
  'news',
  'reportage',
  'go',
  'bit',
  'top',
  'reveal',
  'killer',
  'offer',
  'clever',
  'twist',
  'real',
  'harrisburg',
  'history',
  'look',
  'budd',
  'dwyer',
  'look',
  'true',
  'horror',
  'story',
  'inspired',
  'kill',
  'story',
  'lead',
  'delicious',
  'doozy',
  'climactic',
  'scenemy',
  'real',
  'complaint',
  'another',
  'reviewer',
  'aptly',
  'pointed',
  'way',
  'reader',
  'could',
  'guessed',
  'identity',
  'killer',
  'big',
  'reveal',
  'made',
  'reveal',
  'less',
  'powerhouse',
  'moment',
  'could',
  'made',
  'ponderous',
  'exercise',
  'piecing',
  'together',
  'connection',
  'murder',
  'victim',
  'point',
  'elaborate',
  'jerk',
  'around',
  'reader',
  'expensealso',
  'another',
  'reviewer',
  'pointed',
  'text',
  'contained',
  'typo',
  'careless',
  'error',
  'ever',
  'come',
  'self',
  'respecting',
  'journalist',
  'author',
  'obviously',
  'one',
  'time',
  'go',
  'show',
  'every',
  'writer',
  'need',
  'strong',
  'copy',
  'editorall',
  'however',
  'kill',
  'story',
  'reasonably',
  'well',
  'crafted',
  'thriller',
  'largely',
  'delivers',
  'intriguing',
  'premise',
  'ill',
  'definitely',
  'check',
  'john',
  'luciews',
  'work'],
 ['really',
  'really',
  'wanted',
  'like',
  'book',
  'huge',
  'fan',
  'paranormal',
  'romance',
  'excited',
  'upon',
  'reading',
  'summary',
  'beginning',
  'start',
  'well',
  'introducing',
  'ashley',
  'heroine',
  'christian',
  'hero',
  'setting',
  'amidst',
  'ghostly',
  'atmoshphere',
  'hah',
  'old',
  'worn',
  'pub',
  'thought',
  'two',
  'immediate',
  'chemistry',
  'always',
  'good',
  'thing',
  'spoiler',
  'alert',
  'what',
  'turned',
  'book',
  'among',
  'thing',
  'heroine',
  'constant',
  'incredulity',
  'mean',
  'see',
  'ghost',
  'god',
  'sake',
  'one',
  'would',
  'think',
  'idea',
  'angel',
  'demon',
  'vamp',
  'witch',
  'werewolf',
  'wouldnt',
  'come',
  'much',
  'shock',
  'ala',
  'constantly',
  'surprised',
  'even',
  'willing',
  'deny',
  'existance',
  'everything',
  'around',
  'annoyingthe',
  'thing',
  'drove',
  'absolutely',
  'nut',
  'author',
  'insistance',
  'keeping',
  'ashley',
  'dark',
  'everything',
  'what',
  'seer',
  'apparantly',
  'dad',
  'dad',
  'lurking',
  'basement',
  'christian',
  'ghost',
  'goingthe',
  'list',
  'go',
  'even',
  'maddening',
  'fact',
  'ashley',
  'never',
  'pressed',
  'issue',
  'it',
  'like',
  'fine',
  'completely',
  'obliviousi',
  'understand',
  'appeal',
  'mystery',
  'dont',
  'whack',
  'reader',
  'head',
  'constantly',
  'literally',
  'took',
  'whole',
  'book',
  'ashley',
  'figure',
  'going',
  'problem',
  'could',
  'easily',
  'solved',
  'talked',
  'someone',
  'forced',
  'christian',
  'speak',
  'unfortunately',
  'ticked',
  'point',
  'whole',
  'book',
  'became',
  'frustrating',
  'readthe',
  'one',
  'redeeming',
  'part',
  'character',
  'devoni',
  'really',
  'liked',
  'believe',
  'story',
  'told',
  'next',
  'decided',
  'read',
  'bit',
  'hopefully',
  'isnt',
  'heroine'],
 ['young',
  'love',
  'true',
  'form',
  'especially',
  'young',
  'feline',
  'girl',
  'fell',
  'love',
  'wolf',
  'wolf',
  'pure',
  'blood',
  'felt',
  'way',
  'got',
  'sick',
  'much',
  'changed',
  'young',
  'girl',
  'left',
  'heartbroken',
  'wolf',
  'left',
  'howling',
  'dispaira',
  'year',
  'later',
  'bit',
  'older',
  'wiser',
  'gionne',
  'come',
  'chance',
  'little',
  'feline',
  'jenna',
  'still',
  'love',
  'gionne',
  'changed',
  'doesnt',
  'care',
  'one',
  'wit',
  'mate',
  'right',
  'well',
  'think',
  'bos',
  'around',
  'another',
  'think',
  'coming',
  'literly',
  'purr',
  'thoughtive',
  'book',
  'stash',
  'glad',
  'ran',
  'across',
  'loved',
  'story',
  'flowed',
  'loved',
  'character',
  'especially',
  'razi',
  'gionnes',
  'half',
  'sister',
  'bet',
  'story',
  'bit',
  'mystery',
  'dab',
  'danger',
  'scene',
  'set',
  'sheet',
  'fire',
  'fun',
  'enjoy'],
 ['note',
  'story',
  'appears',
  'bonus',
  'paperback',
  'edition',
  'survivor',
  'quest',
  'fool',
  'bargain',
  'short',
  'story',
  'featuring',
  'stormtroopers',
  'aurek',
  'four',
  'unit',
  'imperial',
  'st',
  'legion',
  'empire',
  'hand',
  'take',
  'place',
  'shortly',
  'event',
  'survivor',
  'quest',
  'probably',
  'best',
  'read',
  'afterthe',
  'empire',
  'hand',
  'involved',
  'war',
  'rid',
  'native',
  'eickarie',
  'people',
  'latest',
  'warlord',
  'st',
  'curious',
  'order',
  'specific',
  'take',
  'warlord',
  'alive',
  'story',
  'tightly',
  'focused',
  'couple',
  'character',
  'firmly',
  'center',
  'there',
  'good',
  'detail',
  'reason',
  'doesnt',
  'feel',
  'well',
  'developed',
  'short',
  'story',
  'ive',
  'read',
  'zahn',
  'also',
  'look',
  'big',
  'name',
  'star',
  'war',
  'story',
  'want',
  'give',
  'pas',
  'couple',
  'minor',
  'character',
  'survivor',
  'quest',
  'show',
  'largely',
  'supporting',
  'role',
  'movie',
  'character',
  'beloved',
  'favorite',
  'herebut',
  'despite',
  'caveat',
  'fool',
  'bargain',
  'good',
  'short',
  'story',
  'give',
  'glimpse',
  'zahns',
  'take',
  'stormtroopers',
  'touched',
  'survivor',
  'quest',
  'would',
  'continue',
  'explore',
  'later',
  'novel',
  'allegiance',
  'choice',
  'one'],
 ['fell',
  'love',
  'jane',
  'porter',
  'couldnt',
  'wait',
  'educated',
  'enter',
  'world',
  'submissive',
  'honor',
  'woman',
  'crave',
  'tutored',
  'hand',
  'doms',
  'priceless',
  'gifti',
  'spellbound',
  'beginning'],
 ['book',
  'sweet',
  'really',
  'annoyed',
  'towards',
  'end',
  'really',
  'stupid',
  'absolutely',
  'loved',
  'stuff',
  'book',
  'thought',
  'bit',
  'much',
  'thought',
  'bit',
  'rushed',
  'overall',
  'thought',
  'really',
  'great',
  'sweet',
  'adorable',
  'touching',
  'romance',
  'novel',
  'would',
  'definitely',
  'recommend',
  'book',
  'anyone',
  'everyone'],
 ['loved',
  'sex',
  'good',
  'story',
  'great',
  'pretty',
  'good',
  'sex',
  'amazing',
  'enjoy',
  'partner'],
 ['expecting',
  'however',
  'good',
  'book',
  'sucked',
  'see',
  'ended',
  'different',
  'good',
  'way',
  'everything',
  'life',
  'prefect',
  'doesnt',
  'mean',
  'bad',
  'good',
  'book',
  'want',
  'read',
  'author'],
 ['short',
  'story',
  'set',
  'world',
  'different',
  'writer',
  'kind',
  'present',
  'day',
  'demon',
  'energymagic',
  'providing',
  'technology',
  'medical',
  'advance',
  'bought',
  'nicole',
  'kimberling',
  'ironically',
  'weakest',
  'piece',
  'liked',
  'world',
  'didnt',
  'mind',
  'think',
  'find',
  'ultimately',
  'forgettable',
  'felt',
  'real',
  'need',
  'buy',
  'hell',
  'cop'],
 ['didnt',
  'think',
  'approach',
  'college',
  'good',
  'sex',
  'lacking',
  'bit',
  'plot',
  'thought',
  'hot',
  'jock',
  'sex',
  'made',
  'interesting',
  'nighttime',
  'reading',
  'thats'],
 ['book',
  'fast',
  'moving',
  'left',
  'disappointed',
  'little',
  'character',
  'development',
  'continuity',
  'like',
  'previous',
  'reviewer',
  'said',
  'choppy',
  'really',
  'would',
  'able',
  'recommend',
  'price',
  'reasonable'],
 ['sherlock',
  'holmes',
  'agatha',
  'christie',
  'enjoy',
  'new',
  'look',
  'csi',
  'could',
  'begun',
  'short',
  'story',
  'break',
  'longer',
  'story',
  'found',
  'kept',
  'becoming',
  'heavy'],
 ['fun',
  'read',
  'like',
  'book',
  'book',
  'read',
  'straight',
  'put',
  'finished'],
 ['reading',
  'entire',
  'cedar',
  'cove',
  'series',
  'found',
  'dull',
  'standard',
  'book'],
 ['coming',
  'age',
  'difficult',
  'time',
  'matter',
  'age',
  'seeking',
  'moment',
  'defines',
  'explains',
  'miss',
  'still',
  'searching'],
 ['pip',
  'come',
  'home',
  'away',
  'year',
  'long',
  'absence',
  'stemming',
  'publicly',
  'rejected',
  'humiliated',
  'lovely',
  'hero',
  'cowboy',
  'course',
  'book',
  'continues',
  'reject',
  'show',
  'place',
  'pip',
  'utterly',
  'pathetic',
  'every',
  'step',
  'way',
  'chasing',
  'didnt',
  'like',
  'honestly',
  'guy',
  'doesnt',
  'call',
  'almost',
  'week',
  'move',
  'pip',
  'little',
  'self',
  'esteem',
  'painful',
  'watch',
  'get',
  'rejected',
  'chase',
  'man',
  'didnt',
  'seem',
  'view',
  'much',
  'hook',
  'book',
  'thought',
  'deserved',
  'manit',
  'also',
  'bugged',
  'slept',
  'serious',
  'relationship',
  'almost',
  'married',
  'pip',
  'sister',
  'nice',
  'interaction',
  'pip',
  'girlfriend',
  'actually',
  'best',
  'book',
  'generally',
  'come',
  'unrealistic',
  'also',
  'fact',
  'universe',
  'book',
  'cowboy',
  'bona',
  'fide',
  'manwhore',
  'acceptable',
  'pip',
  'considered',
  'slut',
  'messed',
  'around',
  'bit',
  'guy',
  'really',
  'rubbed',
  'wrong',
  'way',
  'especially',
  'woman',
  'calling',
  'slut',
  'whore',
  'world',
  'would',
  'author',
  'put',
  'woman',
  'sexual',
  'being',
  'writing',
  'erotica',
  'reader',
  'almost',
  'womenbasically',
  'want',
  'skim',
  'read',
  'sexy',
  'bit',
  'go',
  'wont',
  'disappointed',
  'want',
  'good',
  'story',
  'devoid',
  'cheesy',
  'dialogue',
  'without',
  'hero',
  'total',
  'jerk',
  'heroine',
  'get',
  'rejected',
  'insulted',
  'come',
  'back',
  'might',
  'book',
  'star'],
 ['author',
  'writes',
  'well',
  'story',
  'short',
  'captivating',
  'really',
  'wish',
  'story',
  'lot',
  'longer',
  'storyline',
  'potential'],
 ['never',
  'underestimate',
  'mind',
  'unrehabilitated',
  'criminal',
  'especially',
  'one',
  'planning',
  'next',
  'violent',
  'crime',
  'completing',
  'latest',
  'jail',
  'sentence',
  'simply',
  'put',
  'final',
  'lesson',
  'life',
  'final',
  'crime',
  'thanks',
  'amazon',
  'able',
  'purchase',
  'book',
  'along',
  'others',
  'far',
  'reasonable',
  'cost',
  'convenience',
  'without',
  'reading',
  'material',
  'since',
  'received',
  'kindle'],
 ['first',
  'book',
  'cannon',
  'pack',
  'series',
  'followed',
  'bydance',
  'wilde',
  'sideplotsydneys',
  'family',
  'hunter',
  'hunt',
  'werewolf',
  'shifter',
  'shoot',
  'hang',
  'head',
  'wall',
  'sydney',
  'problem',
  'doesnt',
  'want',
  'hunt',
  'erotic',
  'dream',
  'hunky',
  'shifter',
  'embodiment',
  'dream',
  'jason',
  'save',
  'eaten',
  'vicious',
  'treadmill',
  'life',
  'never',
  'going',
  'samecomments',
  'quite',
  'long',
  'book',
  'kindle',
  'locations',
  'bedroom',
  'scene',
  'spicy',
  'rather',
  'erotic',
  'particularly',
  'frequent',
  'mf',
  'constant',
  'reference',
  'gay',
  'friend',
  'cross',
  'dressing',
  'take',
  'humanshifter',
  'relationship',
  'redneck',
  'hunter',
  'suited',
  'shifter',
  'lot',
  'story',
  'plot',
  'picked',
  'book',
  'sort',
  'promotion',
  'thus',
  'isnt',
  'however',
  'stated',
  'another',
  'reviewer',
  'cost',
  'book',
  'doesnt',
  'really',
  'affect',
  'view',
  'book',
  'either',
  'good',
  'isnt',
  'cost',
  'fluctuates',
  'unfair',
  'judge',
  'based',
  'book',
  'quite',
  'funny',
  'enjoyable',
  'however',
  'didnt',
  'like',
  'enough',
  'search',
  'book',
  'character',
  'strong',
  'interesting',
  'enough',
  'book',
  'could',
  'half',
  'size',
  'still',
  'covered',
  'material',
  'isnt',
  'anything',
  'particularly',
  'wrong',
  'book',
  'okay',
  'light',
  'shifter',
  'book',
  'didnt',
  'grab',
  'much',
  'book',
  'paranormal',
  'genre'],
 ['awful',
  'even',
  'free',
  'total',
  'waste',
  'time',
  'easy',
  'come',
  'free',
  'time',
  'small',
  'child',
  'story',
  'line',
  'interesting',
  'enough',
  'catch',
  'attention',
  'writing',
  'well',
  'story',
  'dreadful',
  'would',
  'advice',
  'someone',
  'read',
  'glutten',
  'punishment'],
 ['book',
  'confused',
  'beginning',
  'way',
  'end',
  'start',
  'without',
  'pre',
  'story',
  'dont',
  'know',
  'anything',
  'character',
  'get',
  'woman',
  'scared',
  'men',
  'two',
  'hot',
  'guy',
  'work',
  'girl',
  'best',
  'friend',
  'set',
  'something',
  'doesnt',
  'really',
  'say',
  'get',
  'hot',
  'steamy',
  'second',
  'book',
  'lacked',
  'detail',
  'developed',
  'character',
  'knowing',
  'detail',
  'made',
  'seem',
  'unbelivable'],
 ['immortal',
  'dark',
  'wonderful',
  'series',
  'book',
  'separately',
  'worth',
  'star',
  'cant',
  'believe',
  'pocket',
  'published',
  'edition',
  'three',
  'lycae',
  'book',
  'put',
  'obscene',
  'price',
  'buy',
  'three',
  'book',
  'separately',
  'like',
  'another',
  'reviewer',
  'say',
  'save',
  'couple',
  'cent',
  'importantly',
  'tell',
  'pocket',
  'give',
  'kresleys',
  'fan',
  'real',
  'deal',
  'passing',
  'one'],
 ['wasnt',
  'overly',
  'impressed',
  'story',
  'plot',
  'character',
  'basically',
  'definitely',
  'would',
  'suggest',
  'book',
  'anyone'],
 ['ive',
  'said',
  'ive',
  'said',
  'hundred',
  'time',
  'crazy',
  'firefighter',
  'firefighter',
  'save',
  'oh',
  'mommy',
  'could',
  'get',
  'firstborn',
  'kid',
  'smirk',
  'suitably',
  'crazy',
  'lynn',
  'lorenz',
  'story',
  'knew',
  'advance',
  'would',
  'love',
  'one',
  'fact',
  'describes',
  'idea',
  'perfect',
  'vacation',
  'didnt',
  'hurt',
  'eithertroy',
  'typical',
  'make',
  'love',
  'spend',
  'enough',
  'time',
  'together',
  'single',
  'guy',
  'dance',
  'book',
  'make',
  'someone',
  'love',
  'isnt',
  'real',
  'he',
  'lusting',
  'idiot',
  'douglas',
  'year',
  'troy',
  'gone',
  'great',
  'length',
  'try',
  'make',
  'attractive',
  'jerk',
  'even',
  'though',
  'troy',
  'best',
  'friend',
  'describes',
  'troy',
  'smart',
  'witty',
  'gorgeous',
  'guy',
  'heart',
  'gold',
  'troy',
  'chance',
  'he',
  'spending',
  'week',
  'cruise',
  'douglas',
  'friend',
  'troy',
  'know',
  'seven',
  'day',
  'douglas',
  'troy',
  'apartment',
  'go',
  'flame',
  'due',
  'neighbor',
  'smoking',
  'sleeping',
  'troy',
  'forced',
  'bathroom',
  'window',
  'balance',
  'precariously',
  'three',
  'story',
  'tiny',
  'ledge',
  'yikeslucky',
  'troy',
  'jason',
  'gorgeous',
  'firefighter',
  'save',
  'brings',
  'ladder',
  'troy',
  'realizes',
  'hospital',
  'one',
  'call',
  'come',
  'pick',
  'cell',
  'phone',
  'wallet',
  'money',
  'home',
  'troy',
  'shocked',
  'jason',
  'appears',
  'hospital',
  'check',
  'even',
  'surprised',
  'jason',
  'offer',
  'let',
  'troy',
  'stay',
  'get',
  'thing',
  'sorted',
  'jason',
  'little',
  'surprised',
  'made',
  'offer',
  'something',
  'troy',
  'rous',
  'protective',
  'possessive',
  'feeling',
  'jason',
  'never',
  'doesnt',
  'take',
  'two',
  'gorgeous',
  'men',
  'long',
  'theyve',
  'fallen',
  'bed',
  'jason',
  'introducing',
  'troy',
  'little',
  'bondage',
  'play',
  'guy',
  'intense',
  'sex',
  'incredible',
  'jason',
  'determined',
  'give',
  'troy',
  'vacation',
  'wont',
  'ever',
  'forget',
  'process',
  'hope',
  'troy',
  'wont',
  'want',
  'leave',
  'friend',
  'come',
  'backthe',
  'vacation',
  'start',
  'jason',
  'getting',
  'troy',
  'much',
  'better',
  'looking',
  'clothes',
  'docker',
  'button',
  'downs',
  'troy',
  'five',
  'year',
  'older',
  'dress',
  'like',
  'old',
  'man',
  'next',
  'lake',
  'day',
  'jet',
  'ski',
  'parasailing',
  'stuff',
  'troy',
  'never',
  'done',
  'blast',
  'jason',
  'take',
  'troy',
  'deep',
  'sea',
  'fishing',
  'fun',
  'troy',
  'ever',
  'jason',
  'doesnt',
  'want',
  'bring',
  'looking',
  'new',
  'apartment',
  'troy',
  'doesnt',
  'either',
  'believe',
  'want',
  'begin',
  'neither',
  'one',
  'want',
  'speak',
  'feeling',
  'fear',
  'hurt',
  'silly',
  'men',
  'haif',
  'enjoy',
  'lighthearted',
  'romance',
  'lot',
  'drama',
  'incredible',
  'amount',
  'sex',
  'might',
  'story',
  'fun',
  'sweet',
  'sexy',
  'good',
  'ending',
  'thank',
  'lynnnote',
  'book',
  'provided',
  'loose',
  'id',
  'purpose',
  'review',
  'rainbow',
  'book',
  'review'],
 ['throughly',
  'enjoyed',
  'selection',
  'series',
  'thought',
  'novella',
  'bit',
  'letdown',
  'even',
  'though',
  'glimpse',
  'restrictive',
  'life',
  'prince',
  'seen',
  'eye',
  'story',
  'maxons',
  'relationship',
  'daphne',
  'seems',
  'one',
  'sided',
  'although',
  'story',
  'give',
  'glimpse',
  'relationship',
  'manipulative',
  'father',
  'view',
  'love',
  'finding',
  'wife',
  'story',
  'redeeming',
  'quality',
  'reveal',
  'maxons',
  'stifling',
  'lifestyle',
  'need',
  'gain',
  'control',
  'life',
  'probably',
  'apparent',
  'perception',
  'selection',
  'meeting',
  'america',
  'need',
  'review',
  'candidate',
  'file',
  'dont',
  'think',
  'need',
  'read',
  'novella',
  'understand',
  'prince',
  'although',
  'entertaining'],
 ['familiar',
  'quotation',
  'book',
  'various',
  'author',
  'great',
  'reference',
  'book',
  'kindle',
  'edition',
  'free',
  'download',
  'enjoyed',
  'looking',
  'favorite',
  'author',
  'shakespere',
  'tennysonlord',
  'byron',
  'wordsworth',
  'excellent',
  'way',
  'look',
  'quote',
  'go',
  'recommend',
  'kindle',
  'edition',
  'anyone'],
 ['book',
  'unrealistic',
  'regretted',
  'reading',
  'time',
  'time',
  'started',
  'reading',
  'days',
  'could',
  'return',
  'tried',
  'trudge',
  'along',
  'without',
  'success',
  'character',
  'development',
  'avid',
  'reader',
  'meacutenage',
  'bdsm',
  'book',
  'heroine',
  'book',
  'came',
  'looking',
  'like',
  'carpet',
  'two',
  'guy',
  'walked',
  'hated',
  'regret',
  'wasting',
  'money'],
 ['ok',
  'prepared',
  'chick',
  'lit',
  'ready',
  'another',
  'dumb',
  'romance',
  'treatment',
  'character',
  'thing',
  'etc',
  'especially',
  'shallow',
  'cannot',
  'forgive',
  'however',
  'misuse',
  'word',
  'book',
  'writer',
  'need',
  'use',
  'spellcheck',
  'find',
  'those',
  'they',
  'need',
  'actually',
  'read',
  'book',
  'started',
  'showing',
  'reason',
  'writer',
  'got',
  'hurry',
  'finish',
  'book',
  'perhaps',
  'sick',
  'toounforgivable',
  'arepeace',
  'pieceshuttered',
  'shudderedsaver',
  'savorknow',
  'nowsummons',
  'summonand',
  'set',
  'look',
  'error',
  'jumped',
  'page',
  'badit',
  'disrupts',
  'entire',
  'thought',
  'process',
  'run',
  'across',
  'stupid',
  'error',
  'like',
  'theseim',
  'glad',
  'pay',
  'book',
  'wasnt',
  'worth',
  'money',
  'read',
  'anything',
  'author',
  'againin',
  'day',
  'age',
  'everyone',
  'seems',
  'think',
  'write',
  'book',
  'easy',
  'write',
  'good',
  'book',
  'suggest',
  'writer',
  'read',
  'good',
  'book',
  'figure',
  'stuff',
  'tripe',
  'author',
  'need',
  'take',
  'english',
  'mistake',
  'unforgivable',
  'anyone',
  'purport',
  'writer',
  'high',
  'school',
  'student',
  'could',
  'write',
  'something',
  'like',
  'this',
  'and',
  'perhaps'],
 ['story',
  'short',
  'sex',

In [84]:
model=gensim.models.Word2Vec(words)

In [85]:
def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if len(vectors) > 0:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.wv.vector_size)

In [86]:
from tqdm import tqdm
import numpy as np

X_train_w2v=[]

for doc in tqdm(words):
    X_train_w2v.append(avg_word2vec(doc))

X_test_w2v=[]

for doc in tqdm(words_test):
    X_test_w2v.append(avg_word2vec(doc))

100%|██████████| 9600/9600 [00:29<00:00, 321.83it/s]
100%|██████████| 2400/2400 [00:07<00:00, 315.23it/s]

In [87]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)
nb_model_w2v=GaussianNB().fit(X_train_w2v,y_train)

In [88]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [89]:
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)
y_pred_w2v=nb_model_w2v.predict(X_test_w2v)
print("Naive Bayes with BoW")
print("Accuracy:", accuracy_score(y_test, y_pred_bow))
print("Classification Report:\n", classification_report(y_test, y_pred_bow))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bow))
print("Naive Bayes with TF-IDF")
print("Accuracy:", accuracy_score(y_test, y_pred_tfidf))
print("Classification Report:\n", classification_report(y_test, y_pred_tfidf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tfidf))
print("Naive Bayes with Word2Vec")
print("Accuracy:", accuracy_score(y_test, y_pred_w2v))
print("Classification Report:\n", classification_report(y_test, y_pred_w2v))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_w2v))

Naive Bayes with BoW
Accuracy: 0.585
Classification Report:
               precision    recall  f1-score   support

           0       0.41      0.66      0.51       778
           1       0.77      0.55      0.64      1622

    accuracy                           0.58      2400
   macro avg       0.59      0.61      0.57      2400
weighted avg       0.66      0.58      0.60      2400

Confusion Matrix:
 [[516 262]
 [734 888]]
Naive Bayes with TF-IDF
Accuracy: 0.5908333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.65      0.51       778
           1       0.77      0.56      0.65      1622

    accuracy                           0.59      2400
   macro avg       0.59      0.61      0.58      2400
weighted avg       0.66      0.59      0.60      2400

Confusion Matrix:
 [[506 272]
 [710 912]]
Naive Bayes with Word2Vec
Accuracy: 0.7004166666666667
Classification Report:
               precision    recall  f1-score   support

           0       0.53      0.72      0.61       778
           1       0.84      0.69      0.76      1622

    accuracy                           0.70      2400
   macro avg       0.68      0.71      0.68      2400
weighted avg       0.74      0.70      0.71      2400

Confusion Matrix:
 [[ 563  215]
 [ 504 1118]]